---
title:       Modelling
subtitle:    Modelling subtitle
description: |
  - model selection
unnumbered:      true
number-sections: false 
editor: source
---

> The selection of modelling techniques must balance interpretability, accuracy, data availability, and computational cost. Given *Pythia’s Advice* aims to build trust and provide transparent, value-added forecasts with minimal resources, **statistical models** were deliberately chosen for their clarity and theoretical grounding. While this choice limits the ability to model promotions and other exogenous factors — potentially reducing accuracy — it supports stakeholder confidence and facilitates adoption. In a future phase, once trust is established, **machine learning** techniques may be explored to further improve forecast performance.


6.1. Literature Review / Similar Models - comprehensive overview of the state of the art in machine learning, including the latest algorithms, - insight into the performance of different algorithms and techniques on similar types of data. (avoid wasting time on models that are unlikely to perform well.)

### Model Selection

different models have different strengths and weaknesses and are suitable for different types of data and problems. achieve the best possible performance and maximize the impact

avoid overfitting a trade-off between the simplicity and flexibility (robustness)

model performance - only article hierarchy - article and customer hierarchy

Cross-validation is a method for evaluating the performance of a model on a validation dataset. This involves dividing the data into k folds, training the model on k-1 folds, and evaluating the performance on the remaining fold. This process is repeated k times, with each fold serving as the validation set once, and the results are averaged to obtain a final performance score. This method provides a more reliable estimate of the model's performance, as it uses all of the data for training and evaluation.

algorithm - handle teh specific characteristics of teh data - balance performance and interpretability - memory and processing power

-   validity -\> fa & prediction intervals
-   robustness -\>
-   transparency -\>

| Capability                   | Standard ARIMA                                        | SARIMA                         | ARIMAX                                        |
| ---------------------------- | ----------------------------------------------------- | ------------------------------ | --------------------------------------------- |
| Handles Trend                | ✅ (via differencing)                                  | ✅ (with seasonal differencing) | ✅                                             |
| Damped Trend                 | ❌ (not explicit)                                      | ❌                              | ❌                                             |
| Seasonality                  | ❌ (needs SARIMA)                                      | ✅                              | ✅                                             |
| Promotions / External Inputs | ❌                                                     | ❌                              | ✅                                             |
| Best For                     | Stationary or differenced series with autocorrelation | Seasonal time series           | Time series influenced by external regressors |



<!-- #### Modeling Technique -->

<!-- #### Modeling Assumptions -->

<!-- ### Generate Test Design -->

<!-- #### Test Design -->

<!-- #### Build Model -->

<!-- ### Parameter Settings -->

<!-- #### Models -->

<!-- #### Model Description -->

<!-- ### Assess Model -->

<!-- #### Model Assessment -->

<!-- #### Revised Parameter Settings -->


# Appendix {.unnumbered}

<!-- {{< include 04_modelling_def.qmd >}} -->
