---
title:       Deployment
subtitle:    Deployment subtitle
description: |
  - scalability - distributed techniques 
  - maintenance & updating the model 
  - monitoring the model 
  - debugging the model
  - model versioning GIT
  -   continuous integration/continuous deployment 
  (CI/CD) pipelines.
unnumbered:      true
number-sections: false
editor: source
---

scalability - distributed techniques - maintenance & updating the model - monitoring the model - debugging the model

# model management

-   model versioning GIT
-   continuous integration/continuous deployment (CI/CD) pipelines.

# Appendix {.unnumbered}

::: callout-note
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-warning
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-important
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-tip
### Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
### Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

<!-- {{< include 06_deployment_def.qmd >}} -->
