project:
  type: book
  output-dir: docs
  # pre-render: "_book_functions.R" 
 
  
date:        last-modified
date-format: long

authors:
  - name:    Floris Padt
    orcid:   0009-0006-4729-1783
    corresponding: true
    email: floris@smart-r.nl
    url: https://www.linkedin.com/in/florispadt    
    roles:
      - Conceptualization
      - Data curation
      - Formal analysis
      - Investigation
      - Methodology
      - Software
      - Validation
      - Visualization
      - Writing     
    degrees: 
      - MSc.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai
  - name:   Ieke Le Blanc
    url: https://www.tue.nl/en/education/professional-education/current-programs/eaisi-academy/lecturers/dr-ieke-le-blanc
    roles:
      - Supervisor
      - Mentor     
    degrees: 
      - Dr.
    affiliations: 
      - name:         EAISI - Technical University Eindhoven
        city:         Eindhoven
        country:      The Netherlands
        department:   EAISI Academy
        group:        Professional education
        url:          https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai 

crossref:
  def-prefix: def
  def-title:  def
    
execute:
  freeze:  auto
  cache:   false
  global:  true  
  echo:    true
  output:  true
  include: true  

editor: source

knitr:
  opts_chunk:
    message: false
    warning: false
    include: true  # Include code by default
    eval:    true  # Evaluate code by default
    echo:    false # Do not show code by default
    output:  true  # Show output by default
  opts_knit:
    # root.dir: "."
    before_chapter_script: "_book_functions.R"  # Remove the "../" 

book:
  title: "Pythia's Advice"
  reader-mode: true
  sidebar:
    style: "floating"
    collapse-level: 1

  page-footer:
    left: "© 2025 Floris Padt: Pythia's Advice"
    # center: ""
    right: "[EAISI](https://www.tue.nl/en/research/institutes/eindhoven-artificial-intelligence-systems-institute/ai-education/professional-education/programs-voor-professionals/mastering-data-ai-mdai)"

  favicon: images/favicon.ico  
  site-url: https://fpadt.github.io/eaisi/
  repo-url: https://github.com/Fpadt/eaisi/
  # repo-branch: main
  repo-actions: [source, issue]
  # image: images/logo_transp.png
 
  downloads: [pdf] 
  sharing: [twitter, facebook, linkedin]
  open-graph: false  

  page-navigation: true # Explicit navigation controls

  chapters:
    # cover + preface
    - index.qmd
    # The myth of Pythia 
    - prophecy_to_prediction.qmd
    # Nicolas van deput
    - setting_the_stage.qmd
        
    #  focus on analysis and findings.
    - part: "The ♥ of Pythia"
      chapters:

        # Introduction
        - notebooks/00_introduction.qmd        
        # - nb/00_introduction_rev.qmd
        # Business Understanding: Analytical Frameworks
        - notebooks/01_business_understanding.qmd
        # - nb/01_business_understanding_rev.qmd
        # Data Understanding: Data Dictionary and Descriptive Statistics        
        - notebooks/02_data_understanding.qmd
        # - nb/02_data_understanding_rev.qmd
        # Data Preparation: Preprocessing Code and Examples
        - notebooks/03_data_preparation.qmd
        # - nb/03_data_preparation_rev.qmd
        # Modelling: Detailed Implementation and Algorithms
        - notebooks/04_modelling.qmd
        # - nb/04_modelling_rev.qmd
        # Evaluation: Performance Metrics and Additional Analysis
        - notebooks/05_evaluation.qmd
        # - nb/05_evaluation_rev.qmd
        # Deployment: Implementation Strategies and Code Snippets
        - notebooks/06_deployment.qmd
        # - nb/06_deployment_rev.qmd
        # Conclusion and Recommendations
        - notebooks/07_conclusions_recommendations.qmd
        # - nb/07_conclusions_recommendations_rev.qmd        
        
    # Recommendations – Suggested actions or further research directions.
    - insight_to_impact.qmd

      # Detailed Analysis and Supplementary Materials
    - part: "Appendix"
      chapters:
        # Business Understanding: Analytical Frameworks
        - notebooks/11_business_understanding.qmd
        # - nb/11_business_understanding_rev.qmd
        # Data Understanding: Data Dictionary and Descriptive Statistics        
        - notebooks/12_data_understanding.qmd
        # - nb/12_data_understanding_rev.qmd
        # Data Preparation: Preprocessing Code and Examples
        - notebooks/13_data_preparation.qmd
        # - nb/13_data_preparation_rev.qmd
        # Modelling: Detailed Implementation and Algorithms
        - notebooks/14_modelling.qmd
        # - nb/14_modelling_rev.qmd
        # Evaluation: Performance Metrics and Additional Analysis
        - notebooks/15_evaluation.qmd
        # - nb/15_evaluation_rev.qmd
        # Deployment: Implementation Strategies and Code Snippets
        - notebooks/16_deployment.qmd
        # - nb/16_deployment_rev.qmd
        # CRISP-DM: Detailed Process Flow – Deeper dive into each phase with coding snippets.
        - notebooks/17_crisp-dm.qmd
        # - nb/17_crisp-dm_rev.qmd        
        # References – Academic references, data sources, and research citations.
        - notebooks/18_references.qmd
        # - nb/18_references_rev.qmd
        # Resources – Tools, libraries, and datasets used, with links and explanations.
        - notebooks/19_resources.qmd
        # - nb/19_resources_rev.qmd
        - package-padt.qmd

resources:
  - notebooks/01_business_understanding.qmd  
  - notebooks/02_data_understanding.qmd
  - notebooks.zip
  - audio/pythia_history.mp3
  - video/glass_blackbox.mp4
  - video/bu_why.mp4  
  - video/bu_who.mp4
  - video/bu_proc.mp4
  - video/mo_method.mp4
  - video/ev_cv.mp4
  - video/ev_compare.mp4  
  - pptx/PAF_s03.pptx

funding: "The author(s) received no specific funding for this work."
categories:
  - Time Series Forecasting
  - Data Science
  - Hierarchical Forecasting (HTS)
  - Error-Trend-Season (ETS)
  - Supply Chain Management
key-points:
  - A RFC-connection was established with the SAP systems leveraging the SAP netweaver software development kit to extract and update the data needed. 
  - Forecast were generated on different levels of aggregation taking the promotional effect into account.
  - A comparison has been made between the differnt forecasts engines in terms of forecast accuracy measures and has been visualized
  - rules of thumb have been developed indicating what to use when
thanks: 'Mentor: {{<var mentor >}} - EAISI Academy, MASTERING DATA & AI, Technical University Eindhoven'
bibliography:      EAISI-PYTHIA.bib
csl:               apa.csl # data-science-journal.csl #apa.csl
# cite-method:       biblatex
# biblio-style:      nature
appendix-style:    default
citation:
  container-title: Pythia's Advice
license: "CC BY"
copyright: 
  holder:          Smart-R
  year:            2025
lang: en-us
nocite: |
  @*

format:
  html:
    callout-appearance: simple
    citation-location: document  
    includes:
      in-header: "_book_functions.R"
    title-block-banner: true
    title-block-style: default
    # Custom banner color
    title-block-banner-color: "#FFFFFF"
    # background-color: "#004D40"
    toc:                true
    toc-depth:          1
    # code-tools: 
      # toggle: true             # Enable toggle button
    code-line-numbers:  true   # Show line numbers
    code-fold:          true   # Enable code folding
    code-fold-default:  hide
    code-overflow:      wrap
    code-highlighting:  pygments  # Options: pygments, highlight.js, default  
    lightbox:           true
    comments:
      hypothesis:       false
    number-sections:    true
    link-citations:     true    
    colorlinks:         true
    highlight-style:    github
    theme:
      light: [flatly, custom-light.scss]
      dark:  [darkly] #, custom-dark.scss]
    respect-user-color-scheme: false    
    fontsize:           "10"
    crossrefs-hover:    true 

  # docx:
  #   reference-doc:      pythia-reference-doc.docx
  #   page-width:         8.27 
  #   toc:                true
  #   toc-depth:          3
  #   toc-title:          'Table of Contents' 
  #   number-sections:    true
  #   number-depth:       2    
  #   number-offset:      0
  #   highlight-style:    github 
  # jats: default
    # documentclass: scrartcl
    # papersize: A4    

  # pdf: #arxiv-pdf:
  #   callout-appearance: simple
  #   citation-location: document
  #   pdf-engine: pdflatex   # or xelatex, lualatex
  #   includes:
  #     in-header: "_book_functions.R"
  #   keep-tex:           false
  #   documentclass:      book #scrbook
  #   # documentclass-options: ["oneside","openany"]
  #   papersize:          a4
  #   include-in-header: header.tex
  #   toc:                true
  #   toc-depth:          1
  #   toc-title:          'Table of Contents'
  #   lof:                false
  #   lot:                false
  #   number-sections:    true
  #   number-depth:       2
  #   number-offset:      0
  #   # mainfont:
  #   # fontfamily: libertinus
  #   # biblio-title:       References
  #   # cite-method:        natbib
  #   fontsize:           "10"
  #   # fontfamily:         Passion One
  #   # sansfont:           Passion One
  #   reference-location: document
  #   citation-location:  document
  #   cap-location:       bottom
  #   fig-cap-location:   top
  #   tbl-cap-location:   top
  #   colorlinks:         true
  #   output-file:        pythias_advice.pdf
  #   linenumbers:        false # Add (continuous) line numbers?
  #   doublespacing:      false # Double space the PDF output?
  #   runninghead:        "Pyhtia's Advice" # The text on the top of each page of the output
  #   authorcols:         false # Should authors be listed in a single column (false)
  # 
