---
title:    Setting the Stage
subtitle: Don't compare your forecasting accuracy to industry benchmarks.
---

<!-- – Inspiration video (introducing aims, scope & “big picture” questions) -->

<!-- – Research objectives, key terminology -->

# Setting the Stage {#sec-setting-the-stage}

The following video by Nicolas Vandeput served as the inspiration for *Pythia’s Advice*. It highlights the importance of establishing a statistical benchmark for forecasting accuracy — one that is both transparent and independent of commercial software or human bias.

Building on this idea, *Pythia’s Advice* aims to generate forecasts using free, open-source, state-of-the-art statistical methods from the [`fable`](https://cran.r-project.org/web/packages/fable/index.html) package developed by Professor [Rob J Hyndman](https://robjhyndman.com/) *et al*. of the Monash University in Melbourne.

These forecasts are designed to require minimal effort, cost, and human intervention, providing a robust and objective reference point. By comparing these statistical forecasts to those produced by the business, we can assess the **Forecast Value Added (FVA)** — a measure of how much value, if any, human-driven forecasting processes bring beyond what data alone can achieve.

</br>

<figure>

{{< video https://www.youtube.com/embed/0f42bR_JF78 title="Don't compare your forecasting accuracy to industry benchmarks." >}}

<blockquote>

Many supply chain leaders are contacting me and ask:\
`how is my forecast accuracy doing compared to my peers?`

I don't think it's the right question. The right question should be:\
`how well is my demand planning team doing compared to a statistical Benchmark?`

I think comparing yourself to your players doesn't make so much sense because every single company has a different set of products, different set of markets, and maybe a different strategy.\
So it means that, maybe simply because you have fewer products than your competitors, it means you're going to have a better or worse forecasting accuracy, that's normal. On top of that, it's extremely expensive and difficult to get the forecasting accuracy of different competitors.

If you want to assess if your team is doing a great or a poor job there is a very easy and simple way to do that:  
`you just have to compare the accuracy achieved by your team to a statistical Benchmark`,  
such as a moving average. It's very easy to do and you can do it for free.\
So I would not hesitate I would simply stick to that.

— Nicolas Vandeput —

</blockquote>

<figcaption>video and insight by <cite>Nicolas Vandeput</cite> (<a href="https://www.supchains.com">supchains.com</a>)</figcaption>

</figure>
