---
subtitle:    Deployment subtitle
description: |
  - scalability - distributed techniques 
  - maintenance & updating the model 
  - monitoring the model 
  - debugging the model
  - model versioning GIT
  -   continuous integration/continuous deployment 
  (CI/CD) pipelines.
number-sections: false
---

# Deployment {#sec-06-deployment}

```{r}
#| label: setup
source("../_book_functions.R")
```

<!--  Deployment – Implications for practical application. -->
<!-- – Practical steps for integration (tools, APIs, monitoring)   -->
<!-- – Change-management considerations -->

scalability - distributed techniques - maintenance & updating the model - monitoring the model - debugging the model

*Pythia’s Advice* will serve as a benchmark in our existing accuracy monitoring system.
To truly derive value from our forecasts, we will start using prediction intervals from E-T-S to determine safety stock levels. 
This method ensures Pythia's Advice will boost sales by preventing stock-outs and minimizing waste. 


This was the ultimate Goal of the *Pythia's Advice* research project!


## model management

-   model versioning GIT
-   continuous integration/continuous deployment (CI/CD) pipelines.


::: callout-note
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-warning
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-important
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-tip
### Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
### Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::


<!-- {{< include 06_deployment_def.qmd >}} -->
